using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._Serenity.Intimacy;
using Content.Shared.Chemistry.Reagent;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Serenity.Intimacy.UI;

/// <summary>
/// Control window for a milking machine: who is strapped in and their stats, the pump mode, and what is in the tank.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class MilkingMachineWindow : FancyWindow
{
    [Dependency] private IPrototypeManager _proto = default!;

    private static readonly Color TankColor = Color.FromHex("#F4EEE1");

    public event Action<MilkingMachineMode>? OnSetMode;

    private readonly Dictionary<MilkingMachineMode, Button> _modeButtons;
    private readonly Dictionary<string, (ProgressBar Bar, Label Value)> _statBars = new();

    public MilkingMachineWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _modeButtons = new()
        {
            [MilkingMachineMode.Off] = OffButton,
            [MilkingMachineMode.Low] = LowButton,
            [MilkingMachineMode.Medium] = MediumButton,
            [MilkingMachineMode.High] = HighButton,
        };

        foreach (var (mode, button) in _modeButtons)
        {
            button.OnPressed += _ => OnSetMode?.Invoke(mode);
        }

        FillBar.ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = TankColor.WithAlpha(0.5f) };
        FillBar.BackgroundStyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#1b1b1b"),
            BorderColor = TankColor.WithAlpha(0.8f),
            BorderThickness = new Thickness(1),
        };

        foreach (var stat in _proto.EnumeratePrototypes<IntimacyStatPrototype>().OrderBy(s => s.Order))
        {
            var bar = new ProgressBar
            {
                MinValue = 0,
                MaxValue = stat.Max,
                HorizontalExpand = true,
                MinHeight = 20,
                ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = stat.Color.WithAlpha(0.65f) },
                BackgroundStyleBoxOverride = new StyleBoxFlat
                {
                    BackgroundColor = Color.FromHex("#1b1b1b"),
                    BorderColor = stat.Color.WithAlpha(0.8f),
                    BorderThickness = new Thickness(1),
                },
            };
            var value = new Label { HorizontalAlignment = HAlignment.Right, Margin = new Thickness(0, 0, 6, 0) };
            bar.AddChild(new Label
            {
                Text = Loc.GetString(stat.Name),
                HorizontalAlignment = HAlignment.Left,
                Margin = new Thickness(6, 0, 0, 0),
            });
            bar.AddChild(value);

            StatsBox.AddChild(bar);
            _statBars[stat.ID] = (bar, value);
        }
    }

    public void UpdateState(MilkingMachineUiState state)
    {
        OccupantLabel.Text = state.OccupantName ?? Loc.GetString("milking-machine-window-empty");
        NotParticipatingLabel.Visible = state.OccupantName != null && !state.OccupantParticipates;
        StatsBox.Visible = state.OccupantName != null && state.OccupantParticipates;

        foreach (var (stat, (bar, label)) in _statBars)
        {
            var value = state.OccupantStats.GetValueOrDefault(stat);
            bar.Value = value;
            label.Text = $"{value:0}";
        }

        // The pressed button is always the current mode, whatever the player clicked last.
        foreach (var (mode, button) in _modeButtons)
        {
            button.Pressed = mode == state.Mode;
        }

        var max = state.MaxVolume.Float();
        FillBar.Value = max > 0f ? state.Volume.Float() / max : 0f;
        FillLabel.Text = Loc.GetString("milking-machine-window-fill",
            ("volume", state.Volume), ("max", state.MaxVolume));

        ContentsBox.RemoveAllChildren();
        if (state.Contents.Count == 0)
        {
            ContentsBox.AddChild(new Label
            {
                Text = Loc.GetString("milking-machine-window-tank-empty"),
                StyleClasses = { "LabelSubText" },
            });
            return;
        }

        foreach (var reagent in state.Contents.OrderByDescending(r => r.Quantity))
        {
            var name = reagent.Reagent.Prototype;
            var color = Color.White;
            if (_proto.TryIndex<ReagentPrototype>(reagent.Reagent.Prototype, out var proto))
            {
                name = proto.LocalizedName;
                color = proto.SubstanceColor;
            }

            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 6 };
            row.AddChild(new PanelContainer
            {
                MinSize = new Vector2(12, 12),
                VerticalAlignment = VAlignment.Center,
                PanelOverride = new StyleBoxFlat { BackgroundColor = color },
            });
            row.AddChild(new Label { Text = name, HorizontalExpand = true });
            row.AddChild(new Label
            {
                Text = Loc.GetString("milking-machine-window-reagent-quantity", ("quantity", reagent.Quantity)),
                StyleClasses = { "LabelSubText" },
            });
            ContentsBox.AddChild(row);
        }
    }
}
