// Ported from Frontier Station 14 at commit 5be37d18c2 (2024-07-01), MIT licensed.
// Copyright (c) 2017-2024 New Frontiers. Adapted for Serenity.

using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Serenity.Shipyard.BUI;
using Content.Shared._Serenity.Shipyard.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Serenity.Shipyard.UI;

[GenerateTypedNameReferences]
public sealed partial class ShipyardConsoleMenu : FancyWindow
{
    [Dependency] private IPrototypeManager _protoManager = default!;

    public event Action<string>? OnPurchase;
    public event Action? OnSellShip;
    public event Action? OnToggleId;
    public event Action? OnSaveShip; // Serenity
    public event Action<string>? OnLoadShip; // Serenity

    private readonly List<string> _categoryStrings = new();
    private string? _category;
    private List<string> _lastProtos = new();
    private bool _accessGranted = true;

    public ShipyardConsoleMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SearchBar.OnTextChanged += _ => PopulateProducts(_lastProtos);
        Categories.OnItemSelected += OnCategoryItemSelected;
        SellShipButton.OnPressed += _ => OnSellShip?.Invoke();
        TargetIdButton.OnPressed += _ => OnToggleId?.Invoke();
        SaveShipButton.OnPressed += _ => OnSaveShip?.Invoke();
    }

    private void OnCategoryItemSelected(OptionButton.ItemSelectedEventArgs args)
    {
        _category = args.Id == 0 ? null : _categoryStrings[args.Id];
        Categories.SelectId(args.Id);
        PopulateProducts(_lastProtos);
    }

    private void PopulateProducts(List<string> prototypes)
    {
        _lastProtos = prototypes;
        Vessels.RemoveAllChildren();

        var vessels = prototypes
            .Select(id => _protoManager.TryIndex<VesselPrototype>(id, out var proto) ? proto : null)
            .Where(proto => proto != null)
            .Cast<VesselPrototype>()
            .OrderBy(proto => proto.Name, StringComparer.CurrentCultureIgnoreCase)
            .ToList();

        var search = SearchBar.Text.Trim().ToLowerInvariant();

        foreach (var proto in vessels)
        {
            var matchesSearch = search.Length == 0 || proto.Name.ToLowerInvariant().Contains(search);
            var matchesCategory = _category == null || proto.Category == _category;
            if (!matchesSearch || !matchesCategory)
                continue;

            var row = new VesselRow
            {
                Vessel = proto,
                VesselName = { Text = proto.Name },
                Purchase = { ToolTip = proto.Description, TooltipDelay = 0.2f, Disabled = !_accessGranted },
                Price = { Text = Loc.GetString("cargo-console-menu-points-amount", ("amount", proto.Price.ToString())) },
            };
            row.Purchase.OnPressed += _ => OnPurchase?.Invoke(proto.ID);
            Vessels.AddChild(row);
        }
    }

    private void PopulateCategories(List<string> prototypes)
    {
        var previous = _category;
        _categoryStrings.Clear();
        Categories.Clear();

        foreach (var id in prototypes)
        {
            if (!_protoManager.TryIndex<VesselPrototype>(id, out var proto))
                continue;

            if (proto.Category.Length > 0 && !_categoryStrings.Contains(proto.Category))
                _categoryStrings.Add(proto.Category);
        }

        _categoryStrings.Sort();
        _categoryStrings.Insert(0, string.Empty);

        for (var i = 0; i < _categoryStrings.Count; i++)
        {
            var text = i == 0
                ? Loc.GetString("cargo-console-menu-populate-categories-all-text")
                : Loc.GetString($"shipyard-console-category-{_categoryStrings[i].ToLowerInvariant()}");
            Categories.AddItem(text, i);
        }

        var index = previous == null ? 0 : Math.Max(0, _categoryStrings.IndexOf(previous));
        _category = index == 0 ? null : _categoryStrings[index];
        Categories.SelectId(index);
    }

    public void UpdateState(ShipyardConsoleInterfaceState state)
    {
        _accessGranted = state.AccessGranted;
        PopulateCategories(state.ShipyardPrototypes);
        PopulateProducts(state.ShipyardPrototypes);

        BalanceLabel.Text = Loc.GetString("cargo-console-menu-points-amount", ("amount", state.Balance.ToString()));
        ShipAppraisalLabel.Text = state.ShipDeedTitle == null
            ? Loc.GetString("shipyard-console-no-deed")
            : Loc.GetString("cargo-console-menu-points-amount", ("amount", state.ShipSellValue.ToString()));
        SellShipButton.Disabled = state.ShipDeedTitle == null;
        TargetIdButton.Text = state.IsTargetIdPresent
            ? Loc.GetString("id-card-console-window-eject-button")
            : Loc.GetString("id-card-console-window-insert-button");
        DeedTitle.Text = state.ShipDeedTitle ?? Loc.GetString("shipyard-console-deed-none");
        SaveShipButton.Disabled = !state.CanSaveShips;
        PopulateSavedShips(state.SavedShips, state.ShipDeedTitle == null && state.IsTargetIdPresent && state.AccessGranted);
    }

    /// <summary>
    /// Serenity: lists the character's saved ships. Loading needs a card with no deed on it, like a purchase.
    /// </summary>
    private void PopulateSavedShips(List<SavedShipEntry> ships, bool canLoad)
    {
        SavedShips.RemoveAllChildren();

        if (ships.Count == 0)
        {
            SavedShips.AddChild(new Label { Text = Loc.GetString("shipyard-console-saved-ships-none") });
            return;
        }

        foreach (var ship in ships)
        {
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, HorizontalExpand = true };
            row.AddChild(new Label { Text = ship.Name, HorizontalExpand = true, ClipText = true });

            var load = new Button
            {
                Text = Loc.GetString("shipyard-console-load", ("fee", ship.LoadFee)),
                Disabled = !canLoad,
            };
            var id = ship.Id;
            load.OnPressed += _ => OnLoadShip?.Invoke(id);
            row.AddChild(load);

            SavedShips.AddChild(row);
        }
    }
}
