## GENERATED by Tools/_Serenity/gen_genital_markings.py

markings-category-Breasts = Breasts
markings-category-Penis = Penis
markings-category-Testicles = Testicles
markings-category-Vagina = Vagina
markings-category-Butt = Butt
markings-category-Belly = Belly

marking-GenitalPenisHumanSmall = Human, small
marking-GenitalPenisHumanAverage = Human, average
marking-GenitalPenisHumanLarge = Human, large
marking-GenitalPenisKnottedSmall = Knotted, small
marking-GenitalPenisKnottedAverage = Knotted, average
marking-GenitalPenisKnottedLarge = Knotted, large
marking-GenitalPenisFlaredSmall = Flared, small
marking-GenitalPenisFlaredAverage = Flared, average
marking-GenitalPenisFlaredLarge = Flared, large
marking-GenitalPenisTaperedSmall = Tapered, small
marking-GenitalPenisTaperedAverage = Tapered, average
marking-GenitalPenisTaperedLarge = Tapered, large
marking-GenitalPenisHemiSmall = Hemipenes, small
marking-GenitalPenisHemiAverage = Hemipenes, average
marking-GenitalPenisHemiLarge = Hemipenes, large
marking-GenitalPenisNondescriptSmall = Nondescript, small
marking-GenitalPenisNondescriptAverage = Nondescript, average
marking-GenitalPenisNondescriptLarge = Nondescript, large
marking-GenitalPenisBarbknotSmall = Barbed and knotted, small
marking-GenitalPenisBarbknotAverage = Barbed and knotted, average
marking-GenitalPenisBarbknotLarge = Barbed and knotted, large
marking-GenitalPenisHemiknotSmall = Knotted hemipenes, small
marking-GenitalPenisHemiknotAverage = Knotted hemipenes, average
marking-GenitalPenisHemiknotLarge = Knotted hemipenes, large
marking-GenitalPenisTentacleSmall = Tentacle, small
marking-GenitalPenisTentacleAverage = Tentacle, average
marking-GenitalPenisTentacleLarge = Tentacle, large

marking-GenitalTesticlesSmall = Pair, small
marking-GenitalTesticlesAverage = Pair, average
marking-GenitalTesticlesLarge = Pair, large
marking-GenitalTesticlesSheathSmall = Sheath, small
marking-GenitalTesticlesSheathAverage = Sheath, average
marking-GenitalTesticlesSheathLarge = Sheath, large

marking-GenitalBreastsSmall = Pair, small
marking-GenitalBreastsMedium = Pair, medium
marking-GenitalBreastsLarge = Pair, large
marking-GenitalBreastsVerylarge = Pair, very large
marking-GenitalBreastsHuge = Pair, huge
marking-GenitalBreastsQuadSmall = Four, small
marking-GenitalBreastsQuadMedium = Four, medium
marking-GenitalBreastsQuadLarge = Four, large
marking-GenitalBreastsQuadVerylarge = Four, very large
marking-GenitalBreastsQuadHuge = Four, huge
marking-GenitalBreastsSextupleSmall = Six, small
marking-GenitalBreastsSextupleMedium = Six, medium
marking-GenitalBreastsSextupleLarge = Six, large
marking-GenitalBreastsSextupleVerylarge = Six, very large
marking-GenitalBreastsSextupleHuge = Six, huge

marking-GenitalButtSmall = Small
marking-GenitalButtAverage = Average
marking-GenitalButtLarge = Large
marking-GenitalButtHuge = Huge

marking-GenitalBellySmall = Small
marking-GenitalBellyMedium = Medium
marking-GenitalBellyLarge = Large
marking-GenitalBellyVerylarge = Very large
marking-GenitalBellyHuge = Huge

marking-GenitalVaginaStandard = Standard
marking-GenitalVaginaTentacle = Tentacle
marking-GenitalVaginaDentata = Dentata
marking-GenitalVaginaHairy = Hairy
marking-GenitalVaginaSpade = Spade
marking-GenitalVaginaFeline = Feline
marking-GenitalVaginaEquine = Equine
marking-GenitalVaginaCervine = Cervine
marking-GenitalVaginaSergal = Sergal
marking-GenitalVaginaHemi = Hemi
marking-GenitalVaginaFurred = Furred
marking-GenitalVaginaPuffy = Puffy
marking-GenitalVaginaGaping = Gaping
marking-GenitalVaginaCloaca = Cloaca
