using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Serenity.Power.Tokamak;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Serenity.Power.Tokamak;

[GenerateTypedNameReferences]
public sealed partial class TokamakConsoleWindow : FancyWindow
{
    private static readonly Color StableColor = Color.FromHex("#6FC938");
    private static readonly Color WarningColor = Color.FromHex("#C49438");
    private static readonly Color DangerColor = Color.FromHex("#BB3232");

    private readonly Dictionary<NetEntity, TokamakDeviceRow> _rows = new();

    private int _fieldStrength;
    private int _minFieldStrength = 1;
    private int _maxFieldStrength = 100;
    private bool _active;

    public event Action<bool>? ActiveToggled;
    public event Action<int>? FieldStrengthChanged;
    public event Action? ScramPressed;
    public event Action<NetEntity, TokamakDeviceSetting, float>? DeviceSettingChanged;

    public TokamakConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        FieldDownLarge.OnPressed += _ => FieldStrengthChanged?.Invoke(Math.Max(_fieldStrength - 10, _minFieldStrength));
        FieldDown.OnPressed += _ => FieldStrengthChanged?.Invoke(Math.Max(_fieldStrength - 1, _minFieldStrength));
        FieldUp.OnPressed += _ => FieldStrengthChanged?.Invoke(Math.Min(_fieldStrength + 1, _maxFieldStrength));
        FieldUpLarge.OnPressed += _ => FieldStrengthChanged?.Invoke(Math.Min(_fieldStrength + 10, _maxFieldStrength));
        PowerButton.OnPressed += _ => ActiveToggled?.Invoke(!_active);
        ScramButton.OnPressed += _ => ScramPressed?.Invoke();
    }

    public void Update(TokamakConsoleBuiState state)
    {
        NoCoreLabel.Visible = !state.HasCore;
        MainBox.Visible = state.HasCore;

        if (!state.HasCore)
            return;

        _active = state.Active;
        _fieldStrength = state.FieldStrength;
        _minFieldStrength = state.MinFieldStrength;
        _maxFieldStrength = state.MaxFieldStrength;

        StateLabel.Text = !state.Powered
            ? Loc.GetString("tokamak-ui-state-unpowered")
            : state.Active
                ? Loc.GetString("tokamak-ui-state-on")
                : Loc.GetString("tokamak-ui-state-off");

        TemperatureLabel.Text = Loc.GetString("tokamak-ui-kelvin", ("value", MathF.Round(state.PlasmaTemperature)));
        OutputLabel.Text = FormatPower(state.PowerOutput);
        DrawLabel.Text = FormatPower(state.PowerDraw);
        RadiationLabel.Text = Loc.GetString("tokamak-ui-number", ("value", MathF.Round(state.RadiationLevel, 1)));
        PlasmaLabel.Text = Loc.GetString("tokamak-ui-plasma-amount",
            ("amount", MathF.Round(state.TotalReactants)),
            ("max", MathF.Round(state.MaxReactants)));

        var instability = Math.Clamp(state.Instability / MathF.Max(1f, state.RuptureInstability) * 100f, 0f, 100f);
        InstabilityBar.Value = instability;
        InstabilityLabel.Text = Loc.GetString("tokamak-ui-percent", ("value", MathF.Round(instability)));
        InstabilityLabel.FontColorOverride = instability switch
        {
            >= 75f => DangerColor,
            >= 50f => WarningColor,
            _ => StableColor,
        };

        FieldStrengthLabel.Text = Loc.GetString("tokamak-ui-number", ("value", state.FieldStrength));
        PowerButton.Text = Loc.GetString(state.Active ? "tokamak-ui-field-off" : "tokamak-ui-field-on");
        ScramButton.Disabled = !state.Active;

        UpdateReactants(state);
        UpdateDevices(state);
    }

    private void UpdateReactants(TokamakConsoleBuiState state)
    {
        ReactantsBox.RemoveAllChildren();

        if (state.Reactants.Count == 0)
        {
            ReactantsBox.AddChild(new Label { Text = Loc.GetString("tokamak-ui-reactants-empty") });
            return;
        }

        foreach (var entry in state.Reactants)
        {
            ReactantsBox.AddChild(new Label
            {
                Text = Loc.GetString("tokamak-ui-reactant-entry",
                    ("reactant", Loc.GetString($"tokamak-reactant-{entry.Reactant}")),
                    ("amount", MathF.Round(entry.Amount, 1))),
            });
        }
    }

    private void UpdateDevices(TokamakConsoleBuiState state)
    {
        NoDevicesLabel.Visible = state.Devices.Count == 0;

        var seen = new HashSet<NetEntity>();
        foreach (var entry in state.Devices)
        {
            seen.Add(entry.Entity);

            if (!_rows.TryGetValue(entry.Entity, out var row))
            {
                row = new TokamakDeviceRow(entry);
                row.SettingChanged += (setting, value) => DeviceSettingChanged?.Invoke(entry.Entity, setting, value);
                _rows[entry.Entity] = row;
                DevicesBox.AddChild(row);
            }

            row.Update(entry);
        }

        foreach (var netEntity in _rows.Keys.ToList())
        {
            if (seen.Contains(netEntity))
                continue;

            DevicesBox.RemoveChild(_rows[netEntity]);
            _rows.Remove(netEntity);
        }
    }

    private static string FormatPower(float watts)
    {
        return watts switch
        {
            >= 1_000_000f => Loc.GetString("tokamak-ui-megawatts", ("value", MathF.Round(watts / 1_000_000f, 2))),
            >= 1_000f => Loc.GetString("tokamak-ui-kilowatts", ("value", MathF.Round(watts / 1_000f, 1))),
            _ => Loc.GetString("tokamak-ui-watts", ("value", MathF.Round(watts))),
        };
    }
}

/// <summary>
/// A row of controls for one gyrotron, injector or harvester. Rows are kept between updates so buttons stay clickable.
/// </summary>
public sealed class TokamakDeviceRow : BoxContainer
{
    private readonly Label _nameLabel = new();
    private readonly Label _statusLabel = new();
    private readonly Label _rateLabel = new();
    private readonly Label _energyLabel = new();
    private readonly Button _toggle = new();

    private TokamakDeviceEntry _entry;

    public event Action<TokamakDeviceSetting, float>? SettingChanged;

    public TokamakDeviceRow(TokamakDeviceEntry entry)
    {
        _entry = entry;
        Orientation = LayoutOrientation.Vertical;

        var header = new BoxContainer { Orientation = LayoutOrientation.Horizontal, SeparationOverride = 6 };
        _nameLabel.HorizontalExpand = true;
        header.AddChild(_nameLabel);
        header.AddChild(_statusLabel);
        AddChild(header);

        var controls = new BoxContainer { Orientation = LayoutOrientation.Horizontal, SeparationOverride = 4 };

        _toggle.OnPressed += _ => SettingChanged?.Invoke(TokamakDeviceSetting.Active, _entry.Active ? 0f : 1f);
        controls.AddChild(_toggle);

        if (entry.Kind != TokamakDeviceKind.Harvester)
        {
            controls.AddChild(MakeStepButton("-", () => SettingChanged?.Invoke(TokamakDeviceSetting.Rate, _entry.Rate - 0.5f)));
            controls.AddChild(_rateLabel);
            controls.AddChild(MakeStepButton("+", () => SettingChanged?.Invoke(TokamakDeviceSetting.Rate, _entry.Rate + 0.5f)));
        }

        if (entry.Kind == TokamakDeviceKind.Gyrotron)
        {
            controls.AddChild(MakeStepButton("-", () => SettingChanged?.Invoke(TokamakDeviceSetting.MegaEnergy, _entry.MegaEnergy - 1f)));
            controls.AddChild(_energyLabel);
            controls.AddChild(MakeStepButton("+", () => SettingChanged?.Invoke(TokamakDeviceSetting.MegaEnergy, _entry.MegaEnergy + 1f)));
        }

        AddChild(controls);
    }

    private static Button MakeStepButton(string text, Action pressed)
    {
        var button = new Button { Text = text };
        button.OnPressed += _ => pressed();
        return button;
    }

    public void Update(TokamakDeviceEntry entry)
    {
        _entry = entry;

        var kind = Loc.GetString($"tokamak-ui-kind-{entry.Kind.ToString().ToLowerInvariant()}");
        _nameLabel.Text = Loc.GetString("tokamak-ui-device-name", ("kind", kind), ("name", entry.Name));

        _statusLabel.Text = entry.Kind == TokamakDeviceKind.Harvester
            ? string.Empty
            : Loc.GetString(entry.Aligned ? "tokamak-ui-aligned" : "tokamak-ui-not-aligned");

        _toggle.Text = Loc.GetString(entry.Active ? "tokamak-ui-device-off" : "tokamak-ui-device-on");

        if (entry.Kind == TokamakDeviceKind.Gyrotron)
        {
            _rateLabel.Text = Loc.GetString("tokamak-ui-gyrotron-rate", ("value", MathF.Round(entry.Rate, 1)));
            _energyLabel.Text = Loc.GetString("tokamak-ui-gyrotron-energy", ("value", MathF.Round(entry.MegaEnergy, 1)));
        }
        else if (entry.Kind == TokamakDeviceKind.Injector)
        {
            _rateLabel.Text = Loc.GetString("tokamak-ui-injector-rate",
                ("value", MathF.Round(entry.Rate, 1)),
                ("fill", MathF.Round(entry.RodFill * 100f)));
        }
    }
}
