using Robust.Shared.Audio;

namespace Content.Shared._Serenity.Power.Tokamak;

/// <summary>
/// The magnetic-confinement core of a tokamak fusion reactor. It holds a plasma made of fusion
/// reactants, which is heated by gyrotrons and fuelled by fuel injectors that point at it.
/// Hot plasma is converted into electrical power on the core's HV cable node.
/// </summary>
[RegisterComponent]
public sealed partial class TokamakCoreComponent : Component
{
    /// <summary>
    /// Whether the magnetic field is switched on.
    /// </summary>
    [DataField]
    public bool Active;

    /// <summary>
    /// Strength of the magnetic field. Higher values raise power output and draw more power,
    /// but also raise the instability pressure on the plasma.
    /// </summary>
    [DataField]
    public int FieldStrength = 10;

    [DataField]
    public int MinFieldStrength = 1;

    [DataField]
    public int MaxFieldStrength = 100;

    /// <summary>
    /// Temperature of the plasma, in kelvin.
    /// </summary>
    [ViewVariables]
    public float PlasmaTemperature = 300f;

    /// <summary>
    /// How close the plasma is to rupturing the field, from 0 to <see cref="RuptureInstability"/>.
    /// </summary>
    [ViewVariables]
    public float Instability;

    /// <summary>
    /// Radiation generated by fusion, decays over time and drives the <c>RadiationSource</c>.
    /// </summary>
    [ViewVariables]
    public float RadiationLevel;

    /// <summary>
    /// Plasma contents, reactant id to amount.
    /// </summary>
    [ViewVariables]
    public Dictionary<string, float> Reactants = new();

    /// <summary>
    /// Electrical power the core is currently supplying, in watts.
    /// </summary>
    [ViewVariables]
    public float PowerOutput;

    /// <summary>
    /// Electrical power the core is currently drawing to hold the field, in watts.
    /// </summary>
    [ViewVariables]
    public float PowerDraw;

    /// <summary>
    /// Total amount of reactants the field can hold.
    /// </summary>
    [DataField]
    public float MaxReactants = 400f;

    /// <summary>
    /// Power drawn from the APC network per point of field strength.
    /// </summary>
    [DataField]
    public float DrawPerFieldStrength = 25f;

    /// <summary>
    /// Fraction of plasma heat radiated away every second.
    /// </summary>
    [DataField]
    public float HeatLossFraction = 0.01f;

    /// <summary>
    /// Coefficient of the temperature to power curve.
    /// </summary>
    [DataField]
    public float OutputCoefficient = 0.05f;

    /// <summary>
    /// Exponent of the temperature to power curve.
    /// </summary>
    [DataField]
    public float OutputExponent = 1.3f;

    /// <summary>
    /// Hard cap on the power the core can supply, in watts.
    /// </summary>
    [DataField]
    public float MaxOutput = 5_000_000f;

    /// <summary>
    /// Temperature above which the plasma becomes harder to hold.
    /// </summary>
    [DataField]
    public float HotPlasmaTemperature = 2_000_000f;

    /// <summary>
    /// Instability at which the field ruptures.
    /// </summary>
    [DataField]
    public float RuptureInstability = 100f;

    /// <summary>
    /// Radius around the core that people disturb the field from.
    /// </summary>
    [DataField]
    public float DisturbanceRange = 2.5f;

    [DataField]
    public string EngineeringChannel = "Engineering";

    [DataField]
    public SoundSpecifier StartSound = new SoundPathSpecifier("/Audio/Machines/ame_fuelinjection.ogg");

    [DataField]
    public SoundSpecifier ShutdownSound = new SoundPathSpecifier("/Audio/Machines/buzz-sigh.ogg");

    [DataField]
    public SoundSpecifier WarningSound = new SoundPathSpecifier("/Audio/Machines/alarm.ogg");

    [DataField]
    public SoundSpecifier RuptureSound = new SoundPathSpecifier("/Audio/Effects/tesla_collapse.ogg");

    /// <summary>
    /// Next time the plasma is simulated.
    /// </summary>
    public TimeSpan NextUpdate;

    /// <summary>
    /// Next time the warning alarm may sound.
    /// </summary>
    public TimeSpan NextWarning;

    /// <summary>
    /// Highest warning stage already announced on the radio.
    /// </summary>
    public int AnnouncedStage;
}
