using System.Globalization;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Serenity.Plumbing.UI;

/// <summary>
///     On/off switch and rate box for a plumbing pump, laid out like the atmos volume pump window.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class PlumbingPumpWindow : FancyWindow
{
    public event Action<bool>? OnToggle;
    public event Action<float>? OnSetRate;

    private float _maxRate;

    public PlumbingPumpWindow()
    {
        RobustXamlLoader.Load(this);

        ToggleStatusButton.OnToggled += _ => OnToggle?.Invoke(ToggleStatusButton.Pressed);

        TransferRateInput.OnTextChanged += _ => SetTransferRateButton.Disabled = false;
        SetTransferRateButton.OnPressed += _ =>
        {
            if (float.TryParse(TransferRateInput.Text, NumberStyles.Float, CultureInfo.CurrentCulture, out var rate))
                OnSetRate?.Invoke(rate);

            SetTransferRateButton.Disabled = true;
        };

        SetMaxRateButton.OnPressed += _ =>
        {
            TransferRateInput.Text = _maxRate.ToString(CultureInfo.CurrentCulture);
            SetTransferRateButton.Disabled = false;
        };
    }

    public void UpdateState(bool enabled, float rate, float maxRate)
    {
        _maxRate = maxRate;
        ToggleStatusButton.Pressed = enabled;
        MaxRateLabel.Text = Loc.GetString("plumbing-pump-window-max", ("max", maxRate));

        // Don't overwrite a value the player is still typing.
        if (!TransferRateInput.HasKeyboardFocus())
            TransferRateInput.Text = rate.ToString(CultureInfo.CurrentCulture);
    }
}
