using System.Globalization;
using System.Numerics;
using Content.Client._Serenity.Economy;
using Content.Client.Stylesheets;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;

namespace Content.Client.Lobby.UI;

/// <summary>
/// Holds character data on the side of the setup GUI.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CharacterPickerButton : ContainerButton
{
    private const string EnabledLoc = "character-setup-gui-character-picker-button-enabled-button";
    private const string DisabledLoc = "character-setup-gui-character-picker-button-disabled-button";

    /// <summary>
    /// Invoked if we should delete the attached character
    /// </summary>
    public event Action? OnDeletePressed;

    /// <summary>
    /// Invoked if we should enable or disable the attached character
    /// </summary>
    public event Action<bool>? OnEnableToggled;

    public HumanoidCharacterProfile Profile { get; private init; }

    // Serenity: the slot whose balance this button shows, if any.
    private readonly int? _slot;
    private CharacterBalanceSystem? _balances;

    /// <summary>
    /// Create a new character picker button
    /// </summary>
    /// <param name="prefMan">Passed in dependency</param>
    /// <param name="protoMan">Passed in dependency</param>
    /// <param name="playerMan">Passed in dependency</param>
    /// <param name="group">Button group to join</param>
    /// <param name="profile">Profile this button is attached to</param>
    /// <param name="isSelected">If true, start in pressed state</param>
    /// <param name="simple">If true, don't show enable or delete button (used for late join gui)</param>
    /// <param name="slot">Serenity: the character's slot, to show its balance; null to show none</param>
    public CharacterPickerButton(
        IClientPreferencesManager prefMan,
        IPrototypeManager protoMan,
        ISharedPlayerManager playerMan,
        ButtonGroup group,
        HumanoidCharacterProfile profile,
        bool isSelected,
        bool simple = false,
        int? slot = null)
    {
        RobustXamlLoader.Load(this);
        AddStyleClass(StyleClassButton);
        ToggleMode = true;
        Group = group;
        Profile = profile;
        _slot = slot;
        View.Initialize(prefMan, protoMan, playerMan); //Starlight
        View.LoadPreview(profile);

        if (profile is HumanoidCharacterProfile humanoid)
        {

            View.Initialize(prefMan, protoMan, playerMan);
            View.LoadPreview(profile);

            EnabledCheck.Pressed = profile.Enabled;
            EnabledCheck.Text = Loc.GetString(profile.Enabled ? EnabledLoc : DisabledLoc);

            Pressed = isSelected;

            DescriptionLabel.Text = View.FullDescription;

            // Set up the StyleBoxTextures for the outlines...
            foreach (var panel in new List<PanelContainer> { EnabledCheckOutline, DeleteButtonOutline })
            {
                if (panel.PanelOverride is not StyleBoxTexture styleBox)
                    continue;
                styleBox.Texture = Theme.ResolveTexture("/Textures/Interface/Nano/slider_outline.svg.96dpi.png");
                styleBox.SetPatchMargin(StyleBox.Margin.All, 12);
                styleBox.SetContentMarginOverride(StyleBox.Margin.All, 0);
                styleBox.SetExpandMargin(StyleBox.Margin.All, 1);
                styleBox.TextureScale = new Vector2(1.1f);
                styleBox.Modulate = StyleNano.PanelDark;
            }

            if (simple)
            {
                ButtonDivider.Visible = false;
                ButtonBox.Visible = false;
            }
            else
            {
                AddStyleClass("OpenRight");
                DeleteButtonOutline.Visible = !isSelected;

                DeleteButton.OnPressed += _ =>
                {
                    OnDeletePressed?.Invoke();
                };

                EnabledCheck.OnToggled += args =>
                {
                    OnEnableToggled?.Invoke(args.Pressed);
                    EnabledCheck.Text = Loc.GetString(profile.Enabled ? EnabledLoc : DisabledLoc);
                };
            }
        }
    }

    // Serenity start: per-character balance
    protected override void EnteredTree()
    {
        base.EnteredTree();

        if (_slot == null)
            return;

        _balances = IoCManager.Resolve<IEntityManager>().System<CharacterBalanceSystem>();
        _balances.BalancesUpdated += UpdateBalance;
        BalanceLabel.Visible = true;
        UpdateBalance();
        _balances.RequestBalances();
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        if (_balances != null)
            _balances.BalancesUpdated -= UpdateBalance;
        _balances = null;
    }

    private void UpdateBalance()
    {
        if (_slot is not { } slot || _balances == null)
            return;

        if (!_balances.TryGetBalance(slot, out var balance, out var startingFunds))
        {
            BalanceLabel.Text = Loc.GetString("character-balance-unknown");
            return;
        }

        var shown = balance.ToString("N0", CultureInfo.InvariantCulture);
        BalanceLabel.Text = startingFunds > 0
            ? Loc.GetString("character-balance-label-starting",
                ("balance", shown), ("starting", startingFunds.ToString("N0", CultureInfo.InvariantCulture)))
            : Loc.GetString("character-balance-label", ("balance", shown));
    }
    // Serenity end
}
